
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import React, { useState } from 'react';
import { XMarkIcon, ShieldCheckIcon, SparklesIcon, ArrowsRightLeftIcon, DocumentDuplicateIcon, CheckIcon, ClipboardDocumentIcon, TrashIcon, ArrowPathRoundedSquareIcon } from '@heroicons/react/24/outline';
import { compareStylesAndGeneratePrompt } from '../services/gemini';

interface AIDetectionModalProps {
  isOpen: boolean;
  onClose: () => void;
  aiContent: string; // The text generated by the app
  onApplyPrompt?: (newPrompt: string) => void; // New prop to handle overwriting settings
}

export const AIDetectionModal: React.FC<AIDetectionModalProps> = ({ 
    isOpen, onClose, aiContent, onApplyPrompt
}) => {
  const [humanText, setHumanText] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [generatedPrompt, setGeneratedPrompt] = useState('');
  const [copied, setCopied] = useState(false);
  const [applied, setApplied] = useState(false);

  const handleAnalyze = async () => {
      if (!aiContent.trim()) {
          alert("左侧没有检测到AI生成的文章，请先在主界面生成。");
          return;
      }
      if (!humanText.trim()) {
          alert("请在右侧粘贴您的原创/对标文章，以便AI进行风格对比。");
          return;
      }

      setIsAnalyzing(true);
      setGeneratedPrompt('');
      setApplied(false);
      
      try {
          const result = await compareStylesAndGeneratePrompt(aiContent, humanText);
          setGeneratedPrompt(result);
      } catch (e) {
          console.error(e);
          setGeneratedPrompt("分析失败，请稍后重试。");
      } finally {
          setIsAnalyzing(false);
      }
  };

  const handleCopyPrompt = () => {
      navigator.clipboard.writeText(generatedPrompt);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
  };

  const handleApplyAndOverwrite = () => {
      if (onApplyPrompt && generatedPrompt) {
          if (confirm("⚠️ 高危操作警告：\n此操作将彻底清除您当前的“文章设置”和“标题设置”，并替换为这套专为通过 AI 检测设计的“逻辑重构指令集”。\n\n确定要覆盖吗？")) {
              onApplyPrompt(generatedPrompt);
              setApplied(true);
              setTimeout(() => {
                  onClose();
              }, 1500);
          }
      }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-in fade-in duration-200">
        <div className="bg-white w-full max-w-7xl h-[90vh] rounded-2xl shadow-2xl flex flex-col overflow-hidden">
            
            {/* Header */}
            <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between bg-white shrink-0">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-indigo-100 rounded-lg">
                        <ShieldCheckIcon className="w-6 h-6 text-indigo-600" />
                    </div>
                    <div>
                        <h2 className="text-xl font-bold text-gray-900">逻辑重构实验室 (Deep Logic Lab)</h2>
                        <p className="text-xs text-gray-500">对比 DeepSeek 等高阶模型与当前文案，一键重构底层思维逻辑</p>
                    </div>
                </div>
                <button 
                    onClick={onClose}
                    className="p-2 hover:bg-gray-100 rounded-full transition-colors text-gray-500"
                >
                    <XMarkIcon className="w-6 h-6" />
                </button>
            </div>

            {/* Main Content: Split View */}
            <div className="flex-1 flex flex-col lg:flex-row overflow-hidden bg-gray-50">
                
                {/* LEFT: AI Content (Read Only) */}
                <div className="flex-1 flex flex-col border-r border-gray-200 m-4 mr-2 bg-white rounded-xl shadow-sm">
                    <div className="px-4 py-3 border-b border-gray-100 bg-red-50/50 flex justify-between items-center">
                        <span className="text-sm font-bold text-red-600 flex items-center gap-2">
                            🤖 当前 AI 生成文案
                        </span>
                        <span className="text-xs text-gray-400">自动提取</span>
                    </div>
                    <div className="flex-1 p-4 overflow-y-auto bg-gray-50/30">
                        <div className="text-sm text-gray-600 leading-relaxed whitespace-pre-wrap">
                            {aiContent || (
                                <span className="text-gray-400 italic">暂无内容，请先在主界面生成文章...</span>
                            )}
                        </div>
                    </div>
                </div>

                {/* CENTER: Action Area (Desktop) */}
                <div className="hidden lg:flex flex-col justify-center items-center gap-4 shrink-0 px-2">
                    <div className="h-full w-px bg-gray-200/50"></div>
                </div>

                {/* RIGHT: Human Content (Editable) */}
                <div className="flex-1 flex flex-col m-4 ml-2 bg-white rounded-xl shadow-sm border border-indigo-100">
                    <div className="px-4 py-3 border-b border-gray-100 bg-indigo-50/50 flex justify-between items-center">
                        <span className="text-sm font-bold text-indigo-600 flex items-center gap-2">
                            🏆 目标样本 (DeepSeek/真人)
                        </span>
                        <span className="text-xs text-gray-400">请在此粘贴</span>
                    </div>
                    <textarea 
                        className="flex-1 p-4 w-full outline-none text-sm text-gray-700 leading-relaxed resize-none bg-transparent placeholder-gray-300"
                        placeholder="请在此粘贴能通过检测的高质量文案（如 DeepSeek 生成的内容）..."
                        value={humanText}
                        onChange={(e) => setHumanText(e.target.value)}
                    />
                </div>
            </div>

            {/* Bottom: Analysis Result & Action */}
            <div className="h-auto min-h-[180px] bg-white border-t border-gray-200 p-6 flex flex-col gap-4 shadow-[0_-10px_40px_rgba(0,0,0,0.05)] z-10">
                {!generatedPrompt ? (
                    <div className="flex flex-col items-center justify-center gap-3 py-4">
                        <p className="text-sm text-gray-500 max-w-2xl text-center">
                            AI 将深度解析右侧文案的<strong className="text-indigo-600">逻辑链条、潜台词密度和起承转合</strong>，
                            并反向生成一套<strong className="text-indigo-600">重构底层思维</strong>的精准指令。
                        </p>
                        <button 
                            onClick={handleAnalyze}
                            disabled={isAnalyzing || !humanText}
                            className={`
                                px-8 py-3 rounded-xl font-bold text-white shadow-lg flex items-center gap-2 transition-all transform hover:scale-105 active:scale-95
                                ${isAnalyzing 
                                    ? 'bg-gray-400 cursor-wait' 
                                    : 'bg-gradient-to-r from-indigo-600 to-purple-600 hover:shadow-indigo-500/30'
                                }
                            `}
                        >
                            {isAnalyzing ? (
                                <>
                                    <ArrowPathIcon className="w-5 h-5 animate-spin" />
                                    正在拆解高维逻辑 (Reconstructing Logic)...
                                </>
                            ) : (
                                <>
                                    <ArrowsRightLeftIcon className="w-5 h-5" />
                                    启动思维模型重构 (Logic Reconstruction)
                                </>
                            )}
                        </button>
                    </div>
                ) : (
                    <div className="flex flex-col h-full animate-in slide-in-from-bottom-4 duration-500">
                        <div className="flex justify-between items-center mb-2">
                            <h3 className="text-sm font-bold text-gray-800 flex items-center gap-2">
                                <SparklesIcon className="w-4 h-4 text-purple-500" />
                                生成的重构指令 (已注入 DeepSeek 级逻辑)
                            </h3>
                            <div className="flex gap-2">
                                <button 
                                    onClick={handleCopyPrompt}
                                    className={`text-xs flex items-center gap-1 px-3 py-1.5 rounded-lg border transition-all ${copied ? 'bg-green-50 text-green-600 border-green-200' : 'bg-white text-gray-600 border-gray-200 hover:border-purple-500 hover:text-purple-600'}`}
                                >
                                    {copied ? <CheckIcon className="w-3 h-3" /> : <ClipboardDocumentIcon className="w-3 h-3" />}
                                    {copied ? "已复制" : "复制指令"}
                                </button>
                                
                                {onApplyPrompt && (
                                    <button 
                                        onClick={handleApplyAndOverwrite}
                                        disabled={applied}
                                        className={`text-xs font-bold flex items-center gap-1 px-4 py-1.5 rounded-lg border transition-all shadow-sm
                                            ${applied 
                                                ? 'bg-green-100 text-green-700 border-green-200' 
                                                : 'bg-red-50 text-red-600 border-red-200 hover:bg-red-100 hover:border-red-300'
                                            }
                                        `}
                                    >
                                        {applied ? (
                                            <>
                                                <CheckIcon className="w-3 h-3" />
                                                已重构设置!
                                            </>
                                        ) : (
                                            <>
                                                <ArrowPathRoundedSquareIcon className="w-3 h-3" />
                                                应用并重构思维 (慎点)
                                            </>
                                        )}
                                    </button>
                                )}
                            </div>
                        </div>
                        <div className="relative flex-1 bg-gray-50 rounded-xl border border-gray-200 p-4 overflow-y-auto">
                            <pre className="whitespace-pre-wrap font-mono text-xs text-gray-700 leading-relaxed">
                                {generatedPrompt}
                            </pre>
                        </div>
                        <p className="text-xs text-center text-gray-400 mt-2">
                            点击“应用并重构”将自动替换主界面的“文章设置”，让 AI 彻底换脑。
                        </p>
                    </div>
                )}
            </div>
        </div>
    </div>
  );
};

// Helper icon
function ArrowPathIcon({ className }: { className?: string }) {
    return <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}><path strokeLinecap="round" strokeLinejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0013.803-3.7M4.031 9.865a8.25 8.25 0 0113.803-3.7l3.181 3.182m0-4.991v4.99" /></svg>
}
